# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.4-x86_64"

  config.vm.provider :virtualbox do |v, override|
   # Disable the base shared folder, guest additions are unavailable.
   #config.vm.synced_folder ".", "/vagrant", disabled: true
   #v.gui = true
   #v.customize ["modifyvm", :id, "--memory", "1024"]

    # bond0: eth1, eth2
    v.customize ["modifyvm", :id, "--nic2",   "intnet"]
    v.customize ["modifyvm", :id, "--nic3",   "intnet"]
    v.customize ["modifyvm", :id, "--intnet2", "bond0"]
    v.customize ["modifyvm", :id, "--intnet3", "bond0"]
    # bond1: eth3, eth4
    v.customize ["modifyvm", :id, "--nic4",   "intnet"]
    v.customize ["modifyvm", :id, "--nic5",   "intnet"]
    v.customize ["modifyvm", :id, "--intnet4", "bond1"]
    v.customize ["modifyvm", :id, "--intnet5", "bond1"]
    # bond2: eth5, eth6
    v.customize ["modifyvm", :id, "--nic6",   "intnet"]
    v.customize ["modifyvm", :id, "--nic7",   "intnet"]
    v.customize ["modifyvm", :id, "--intnet6", "bond2"]
    v.customize ["modifyvm", :id, "--intnet7", "bond2"]
  end

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "config.d/base.sh"

  config.vm.define "node01" do |node|
    node.vm.hostname = "node01"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
  end

  config.vm.define "node02" do |node|
    node.vm.hostname = "node02"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
  end
end
